<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: tan;">
    <script>
        const promise1= new Promise ( function (resolve,reject){
    setTimeout( function(){
        resolve()
        console.log("promise is completed")
    },1000)

})
 const response = promise1.then(function(){
console.log("promise ")
})

const promise2 = new Promise (function (resolve,reject){
    setTimeout( function()  {
        let response = true
        if(response){
            resolve()
        }else {
            reject("something went wrong")
        }
    },0);
}) 
promise2.then(()=> console.log("promise is completed now"))
.catch((error)=> console.log("caught error :",error))

 const promise3 = new Promise (function (resolve,reject){
    setTimeout(() => {
        let error = true
        if(!error){
            resolve({username: "ujjwal",password: 123})
        
        }else{
             reject('server is not responding')
        }
    },1000);
 }) .then(( naam)=> {
    console.log (naam)
    return (naam.username)
 }).then((naam)=>{
console.log(naam)
 }).catch((error)=>{
    console.log("ERROR CAUGHT",error)
 })

const promiseFour = new Promise (function (resolve,reject){
    setTimeout(() => {
        let error = false
        if(!error){
            resolve({username: "ujjwal",password: 123})
        
        }else{
             reject('server is not responding')
        }
    },1000);
})
async function consumepromiseFour(naam) {
    try{
     let response = await promiseFour
     console.log(response)
    }catch (error){
console.log("ERROR CAUGHT", error)
    }
}
const promiseFive = new Promise (function(resolve,reject){
setTimeout(() => {
    let error = false
    if(!error){
        resolve({language: "javascript", libraray: "node.js"})
    }else{
        reject("Server is slow")
    }
},1000);
})
async function consumepromiseFive(user){
    try{
        let result = await promiseFive
        console.log(result)
    }catch(error){
        console.log("ERROR IS FOUND:",error)
    }
}
let promiseSix = new Promise((resolve,reject)=>{
    let wrong = false
    setTimeout(()=>{
if(!wrong){
    resolve()
    console.log("your data will be received")
    
}else{
    reject("server is under maintaianeace")
}
    },1000)
})
.then(()=>{
    console.log("so your ragistration succesfull")
})
.catch((wrong)=> console.log("error caught :", wrong))

/* Create a promise that resolves after 2 seconds with the message "Done!".

Make a function that returns a Promise, which resolves if the input number is even and rejects if it's odd.*/

const promise = new Promise ((resolve,reject)=>{
    setTimeout(() => {
        console.log("done!")
resolve()
    }, 2000);
})

function promi(){
    const ujjwal = new Promise((resolve,reject)=>{
        setTimeout(() => {
            let num = 2;
            if(num%2===0){
             resolve()
             console.log("number is even")
            }else {
                reject("it is odd")
            }
        }, 1000);
    }).then((data)=>{
    console.log("yes it is even")
}).catch((error)=>{
    console.log(error)
})
}
let ujj = promi()
console.log(ujj)


    </script>
</body>
</html>